baseURL: "https://lordWalnuts.github.io/deeplymind"
languageCode: en-us
title: DeeplyMind
theme: "PaperMod"
paginate: 5

enableInlineShortcodes: true
disqusShortname: deeply-mind
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true


minify:
    disableXML: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
     
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Theme PaperMod

    defaultTheme: auto
    ShowShareButtons: false
    ShowReadingTime: false
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    TocOpen: True
    comments: true



    homeInfoParams:
        Title: "Deeply Mind"
        Content: >
            Welcome to Deeply Mind

            - I write articles on Deep Learning and document my journey through learning AI

            - Follow me on [Twitter](https://twitter.com/lordWalnuts) and [Github](https://github.com/lordWalnuts)


    socialIcons:
        - name: email
          url: "mailto:brkoushik99work@gmail.com"
        - name: github
          url: "https://github.com/lordWalnuts"
        - name: Twitter
          url: "https://twitter.com/lordWalnuts"
        - name: KoFi
          url: "ko-fi.com/deeplymind"
        # - name: PayPal
        #   url: "www.paypal.com"
        # - name: Patreon
        #   url: "www.patreon.com"
        - name: Rss
          url: "index.xml"

    assets:
        disableHLJS: true



markup:
    goldmark:
        renderer:
            unsafe: true
            highlight:
              codeFences: true
              guessSyntax: true

              noHl: false
              style: monokai
              tabWidth: 4

